UnivMVC.Web/Controllers/CtaCteController.cs
using Microsoft.AspNetCore.Mvc;
using UnivMVC.Application.Interfaces;

namespace UnivMVC.Web.Controllers
{
    public class CtaCteController : Controller
    {
        private readonly ICtaCteService _ctaCteService;

        public CtaCteController(ICtaCteService ctaCteService)
        {            
            _ctaCteService = ctaCteService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {            
            int estudiante_id = HttpContext.Session.GetInt32("estudiante_id") ?? 0;
            int semestre_id = HttpContext.Session.GetInt32("semestre_id") ?? 0;

            if (estudiante_id <= 0 || semestre_id <= 0)
            {
                return RedirectToAction("Index", "Auth");
            }            

            var listaOfertaAcad = await _ctaCteService.ConsultarEstadoCtaCteAsync(estudiante_id, semestre_id);

            return View(listaOfertaAcad);
        }
    }
}

UnivMVC.Web/Controllers/MatriculaController.cs
using Microsoft.AspNetCore.Mvc;
using UnivMVC.Application.Interfaces;
using UnivMVC.Application.DTOs;

namespace UnivMVC.Web.Controllers
{
    public class MatriculaController : Controller
    {
        private readonly IAcademicService _academicService;
        private readonly ICtaCteService _ctaCteService;

        public MatriculaController(IAcademicService academicService, ICtaCteService ctaCteService)
        {
            _academicService = academicService;
            _ctaCteService = ctaCteService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<int> horariosMat = new();

            int estudiante_id = HttpContext.Session.GetInt32("estudiante_id") ?? 0;
            int semestre_id = HttpContext.Session.GetInt32("semestre_id") ?? 0;
            int categoria_id = HttpContext.Session.GetInt32("categoria_id") ?? 0;

            int matriculaId = HttpContext.Session.GetInt32("matricula_id") ?? 0;

            string error = TempData["matricularme_error"]?.ToString() ?? "";

            if (estudiante_id <= 0)
            {
                return RedirectToAction("Index", "Auth");
            }

            ViewBag.Error = error;

            var pagoMatricula = await _ctaCteService.ConsultarPagoMatriculaAsync(estudiante_id, semestre_id, categoria_id);

            if (pagoMatricula == null) {
                ViewBag.Error = "No se pudo confirmar el pago por el derecho de matrícula.";
                return View();
            }

            if (pagoMatricula.respuesta <= 0)
            {
                ViewBag.Error = pagoMatricula.mensaje;
                return View();
            }

            var listaOfertaAcad = await _academicService.ObtenerOfertaAcademicaAsync(estudiante_id);
            var listaCursosMat = await _academicService.ObtenerCursosMatriculadosAsync(matriculaId);

            foreach (var cursoMat in listaCursosMat)
            {
                horariosMat.Add(cursoMat.id);
            }

            ViewBag.HorariosMat = horariosMat;

            return View(listaOfertaAcad);
        }

        [HttpPost]
        public async Task<IActionResult> Index(Dictionary<int, int> Horarios)
        {
            MatriculaDto matriculaDto = new();

            //Nada seleccionado
            if (Horarios.Count <= 0)
            {
                TempData["matricularme_error"] = "Debe seleccionar al menos un curso.";                

                return RedirectToAction("Index");
            }

            //Objeto para consumo de endpoint de matrícula
            matriculaDto.estudiante_id = HttpContext.Session.GetInt32("estudiante_id") ?? 0;
            matriculaDto.semestre_id = HttpContext.Session.GetInt32("semestre_id") ?? 0;
            matriculaDto.categoria_id = HttpContext.Session.GetInt32("categoria_id") ?? 0;            

            foreach (var item in Horarios)
            {
                Horario horario = new Horario();

                horario.curso = item.Key;
                horario.horario = item.Value;

                matriculaDto.horarios.Add(horario);                
            }

            //Consumir endpoint de matrícula            
            var listaCursosMat = await _academicService.RegistrarMatriculaAsync(matriculaDto);
            
            if (listaCursosMat == null || listaCursosMat.Count <= 0)
            {
                //Regresar a la vista porque algo salió mal
                var listaOfertaAcad = await _academicService.ObtenerOfertaAcademicaAsync(matriculaDto.estudiante_id);

                ViewBag.HorariosSeleccionados = Horarios;                
                ViewBag.Error = "No se pudo registrar la matrícula. Inténtalo nuevamente.";

                return View("Index", listaOfertaAcad);                
            }

            HttpContext.Session.SetInt32("matricula_id", listaCursosMat[0].matricula_id);

            return RedirectToAction("Horario");
        }

        [HttpGet]
        public async Task<IActionResult> Horario()
        {
            int matriculaId = HttpContext.Session.GetInt32("matricula_id") ?? 0;
            int estudiante_id = HttpContext.Session.GetInt32("estudiante_id") ?? 0;

            if (estudiante_id <= 0)
            {
                return RedirectToAction("Index", "Auth");
            }

            var listaCursosMat = await _academicService.ObtenerCursosMatriculadosAsync(matriculaId);

            return View(listaCursosMat);
        }
    }
}

UnivMVC.Web/Controllers/PrincipalController.cs
using Microsoft.AspNetCore.Mvc;

using UnivMVC.Application.Interfaces;
using UnivMVC.Application.DTOs;
using System.Net;

namespace UnivMVC.Web.Controllers
{
    public class PrincipalController : Controller
    {
        private readonly IAcademicService _academicService;

        public PrincipalController(IAcademicService academicService)
        {
            _academicService = academicService;
        }

        public async Task<IActionResult> Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usr")))
            {
                return RedirectToAction("Index", "Auth");
            }

            int personaId = HttpContext.Session.GetInt32("persona_id") ?? 0;
            string nombre_usuario = HttpContext.Session.GetString("nombre_usuario") ?? "";
            string doc_id = HttpContext.Session.GetString("doc_id") ?? "";

            var estudiante = await _academicService.ObtenerEstudianteInfoAsync(personaId);

            if (estudiante.status == HttpStatusCode.InternalServerError)
            {
                ViewBag.Error = "Error de conexión con el servicio académico";

                return View();
            }

            if (estudiante.id <= 0)
            {
                ViewBag.Error = "El usuario no figura como un estudiante registrado";

                return View();
            }

            HttpContext.Session.SetInt32("estudiante_id", estudiante.id);
            HttpContext.Session.SetInt32("semestre_id", estudiante.semestre_id);
            HttpContext.Session.SetInt32("categoria_id", estudiante.categoria_id);
            HttpContext.Session.SetString("sede", estudiante.sede);
            HttpContext.Session.SetString("facultad", estudiante.facultad);
            HttpContext.Session.SetString("programa", estudiante.programa);
            HttpContext.Session.SetString("semestre", estudiante.semestre);
            HttpContext.Session.SetInt32("matricula_id", estudiante.matricula_id);

            ViewBag.Error = "";

            return View();
        }
    }
}

UnivMVC.Web/Views/Shared/_EstudianteInfo.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var semestre = HttpContextAccessor.HttpContext?.Session?.GetString("semestre") ?? "";
    var nombre_usuario = HttpContextAccessor.HttpContext?.Session?.GetString("nombre_usuario") ?? "";
    var sede = HttpContextAccessor.HttpContext?.Session?.GetString("sede") ?? "";
    var facultad = HttpContextAccessor.HttpContext?.Session?.GetString("facultad") ?? "";
    var programa = HttpContextAccessor.HttpContext?.Session?.GetString("programa") ?? "";    
}

<div class="fw-bold p-1" style="font-size: 0.75rem; border: 1px solid green; border-radius: 5px;">
    <span>Semestre: @semestre</span><br />
    <span>Estudiante: @nombre_usuario</span><br />
    <span>Sede: @sede</span><br />
    <span>Facultad: @facultad</span><br />
    <span>Programa: @programa</span><br />
</div>

<br />

UnivMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Grupo 01 - Matrícula Virtual</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index">Matrícula Virtual</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UnivMVC.Web/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Grupo 01 - Matrícula Virtual</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Auth" asp-action="Index">Matrícula Virtual 1.0</a>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UnivMVC.Web/Views/Shared/_Layout_Principal.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Grupo 01 - Matrícula Virtual</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Principal" asp-action="Index">Matrícula Virtual 1.0</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Matricula" asp-action="Index">Matrícula</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Matricula" asp-action="Horario">Horario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="CtaCte" asp-action="Index">Estado Cta. Cte.</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <nav class="navbar fixed-bottom navbar-dark bg-success text-white p-0 p-1" style="font-size: 0.7rem;">
            <div class="container-fluid">
                <span>© Grupo 01 - Antonio Estrada, Carlos Peña</span>
            </div>
        </nav>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>